import Providers from "@/components/providers";
import { gitlabmono, incognito } from "@/fonts/font";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Navbar } from "@/components/dock";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${incognito.variable} ${geistSans.variable} ${gitlabmono.variable} dark:bg-zinc-900 bg-white dark:text-white text-zinc-700 relative`}
            >
                <Providers>
                    <Navbar />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
